# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93a1d920046b3089d3003983442b7de9f593256557278e68f2991e16d307cf205519a52b4037410742b43557b5cbc8bcc1f165e4cb5e38d72351bc01d9528b47

test:
  secret_key_base: bce1a2ccc7dcdedbeead4f41f98528ac3d75190e9ea8a3db62813108765fcca7f3d63a919bb0f3d8a0647f2b10a93f56cb66ee650da48030748bb26f076bed7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
